### ISSUE TITLE
Duplicate Organization!

### ISSUE THREAD

**Issue by Mayank-Khurmai** [OSS-CONFERENCE/oss_conf#7]
@Ishank-811 @freakyLuffy @Shivangi-ch 
This respository should be under the https://github.com/ossrndc not anywhere else. 
So, please either transfer this repository to [OSSRNDC](https://github.com/ossrndc) or create a new one on [OSSRNDC](https://github.com/ossrndc)
And after that, delete this repo as well as [OSS-CONFERENCE](https://github.com/OSS-CONFERENCE) organization from the Github.

**Comment by freakyLuffy** [comment]
Okay sir , will do.
